### PR TITLE
Reader writer

### PR DESCRIPTION
**Pull request by D-moe**
Reader writer implementation in the MVP, Frelicia's changes should be placed on top of this branch for merging (Some comments in her prior pull request will apply here).

### CODE REVIEW

**Comment by zjwoody** [comment]
Can it be included in pr15?
Is pr#15 based on this branch? can you revert this branch and merge it with pr#15's branch, so we don't need to checkin this one.

**Comment by D-moe** [comment]
The relevant changes in pr 15 should be made to this branch. It would not be wise to try to merge the current contents or or 15 as it’s git history contains many deletes of crucial files that will lead to a large amount of merge conflicts and a convoluted commit history

**Comment by D-moe** [comment]
I specifically created this branch from the relevant parts of the commit history from before pr 15 was committed instead of the files being manually copied over and then all deleted.

**Comment by D-moe** [comment]
Ideally pr 15 will be closed and the relevant commits will be cherry picked to this branch ridding us of merge conflicts and making a readable history of commits.

**Comment by freliciatucker** [comment]
should this PR be deleted?

**Comment by D-moe** [comment]
Yeah maybe it should be deleted, if I have a minute I'll look into fixing the git history one last time, so lets leave it for now.

**Pull request closed without merging**
